apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
      server {
        listen 8080;
        location / {
          return 200 "Hello, world!";
        }
      }
    }
    events {}
